import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/src/components/Header/Header";
import QueryProvider from "@/src/app/providers/QueryProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'anonimno.bg',
  description: 'Generated by Veliko and Nikolay',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      	<QueryProvider>
        <Header />
        	{children}
	  	  </QueryProvider>
      </body>
    </html>
  )
}
